name: Create Full Flutter App

on:
  workflow_dispatch:  # اجرا به‌صورت دستی

jobs:
  create-flutter-app:
    runs-on: ubuntu-latest

    steps:
      - name: 🧾 Checkout repository
        uses: actions/checkout@v3

      - name: 🛠️ Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: stable

      - name: 🧱 Create full Flutter project
        run: |
          flutter create --org com.example --project-name my_app --platforms android,ios,linux,macos,web,windows my_app
          cd my_app

          # ساختار حرفه‌ای
          mkdir -p lib/src/screens
          mkdir -p lib/src/widgets
          mkdir -p lib/src/models
          mkdir -p lib/src/services
          mkdir -p assets/images
          mkdir -p assets/icons
          mkdir -p test/widgets

          # اضافه کردن asset ها در pubspec.yaml
          sed -i '/^dependencies:/a\  cupertino_icons: ^1.0.6' pubspec.yaml
          sed -i '/^flutter:/a\\ \ assets:\n\ \ \ \ - assets/images/\n\ \ \ \ - assets/icons/' pubspec.yaml

          flutter pub get

      - name: 📤 Commit and push new Flutter project
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"

          cp -r my_app/* .
          cp -r my_app/.* . || true
          rm -rf my_app

          git add .
          git commit -m "🚀 Full Flutter project created with all platforms and structure" || echo "No changes"
          git push origin HEAD
