name: Build and Deploy Flutter Web

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: ðŸ“¥ Checkout code
        uses: actions/checkout@v3

      - name: ðŸ’» Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "stable"

      - name: ðŸ§ª Install dependencies
        run: flutter pub get

      - name: ðŸ—ï¸ Build Flutter Web
        run: flutter build web

      - name: ðŸ” Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.CI_SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: ðŸš€ Push to repo (web build)
        run: |
          git config --global user.email "ci@github.com"
          git config --global user.name "GitHub CI"
          git clone git@github.com:dilagh01/metreyar_flutter_web.git deploy_repo
          cd deploy_repo
          rm -rf *
          cp -r ../build/web/* .
          git add .
          git commit -m "ðŸš€ Auto-deploy Flutter Web on $(date)" || echo "Nothing to commit"
          git push origin main
