name: 🚀 Create & Deploy Full Flutter App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  create-deploy-flutter-app:
    runs-on: ubuntu-latest

    steps:
      - name: 🔄 Checkout repository
        uses: actions/checkout@v3

      - name: 🛠️ Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: stable

      - name: 🧱 Create full Flutter project
        run: |
          rm -rf ./* .[^.]*
          flutter create --org com.example --project-name my_app --platforms android,ios,linux,macos,web,windows my_app
          cd my_app

          mkdir -p lib/src/screens
          mkdir -p lib/src/widgets
          mkdir -p lib/src/models
          mkdir -p lib/src/services
          mkdir -p assets/images
          mkdir -p assets/icons
          mkdir -p test/widgets

          sed -i '/^dependencies:/a\  cupertino_icons: ^1.0.6' pubspec.yaml
          sed -i '/^flutter:/a\\ \ assets:\n\ \ \ \ - assets/images/\n\ \ \ \ - assets/icons/' pubspec.yaml

          flutter pub get

          cp -r . ../
          cd ..
          rm -rf my_app

      - name: 📤 Commit and Push Flutter project
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "🚀 Recreated Flutter project with full structure" || echo "Nothing to commit"
          git push origin HEAD

      - name: 🌐 Build Flutter web
        run: flutter build web

      - name: 🚀 Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
          publish_branch: gh-pages
