name: metreyar
description: A new Flutter project.
publish_to: 'none' # Remove this if you plan to publish on pub.dev

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Charts
  fl_chart: ^0.66.2

  # Navigation & State Management (ساده‌ترین انتخاب)
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  go_router: ^14.2.3
  data_table_2: ^2.5.18
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
