name: metreyar_flutter_web
description: "Metreyar Flutter Web Application"

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  file_picker: ^5.5.0  # ✅ استفاده از file_picker عمومی به جای file_picker_web

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
