name: metreyar
description: A new Flutter project.
publish_to: 'none' # Remove this if you plan to publish on pub.dev

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Charts
  fl_chart: ^0.66.2

  # Navigation & State Management (ساده‌ترین انتخاب)
  cupertino_icons: ^1.0.8
  provider: ^6.0.5
  go_router: ^6.5.0
  data_table_2: ^2.6.0
  flutter_riverpod: ^2.4.9
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.15
  excel: ^2.0.1
  file_picker: ^10.3.2
  printing: ^5.11.0
  pdf: ^3.10.4
  open_file: ^3.3.1  # یا آخرین نسخه
  http: ^0.13.5
  syncfusion_flutter_pdf: ^23.1.44
  syncfusion_flutter_datagrid: ^23.1.44
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
