name: metreyar_flutter_web
description: A Flutter project for Web and Android
publish_to: 'none'

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.0.4
  google_ml_kit: ^0.16.3
  http: ^1.2.1
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
