name: metreyar_flutter_web
description: A new Flutter project
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^1.2.1
  go_router: ^13.2.1
  sentry_flutter: ^8.0.0
  file_picker: ^6.1.1
  logger: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
