name: Flutter Web Build

on:
  push:
    branches: [ index ]
    paths:
      - '**.dart'
      - 'pubspec.yaml'
      - 'Dockerfile'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.6'

      - name: Install dependencies
        run: flutter pub get

      - name: Build Flutter Web
        run: flutter build web

      - name: Upload build
        uses: actions/upload-artifact@v4
        with:
          name: flutter_web_build
          path: build/web
