name: Deploy Flutter Web to GitHub Pages

on:
  push:
    branches:
      - main  # یا اگر شاخه‌ات "master" است، آن را جایگزین کن

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.1'  # مطمئن شو با نسخه پروژه‌ات هماهنگ است

      - name: Install dependencies
        run: flutter pub get

      - name: Build Flutter Web
        run: flutter build web --web-renderer html --no-tree-shake-icons

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/web
