name: Deploy Flutter Web to GitHub Pages

on:
  push:
    branches:
      - main  # اگر شاخه اصلیت اسم دیگری است، اینجا عوض کن

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.19.5"

      - name: Enable Web
        run: flutter config --enable-web

      - name: Get Dependencies
        run: flutter pub get

      - name: Build Flutter Web
        run: flutter build web --base-href="/"

      - name: Add CNAME file
        run: |
          echo "homkar.ir" > build/web/CNAME

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/web
