name: Flutter Build All Platforms

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    env:
      FLUTTER_CHANNEL: stable
      FLUTTER_VERSION: 3.32.8  # می‌تونی این رو آخرین نسخه تغییر بدی
      FLUTTER_STORAGE_BASE_URL: https://mirrors.tuna.tsinghua.edu.cn/flutter

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: ${{ env.FLUTTER_CHANNEL }}

      - name: Flutter pub get
        run: flutter pub get

      - name: Build Android APK
        run: flutter build apk --release

      - name: Build iOS archive (no codesign)
        run: flutter build ios --release --no-codesign

      - name: Build Web release
        run: flutter build web --release

      - name: Upload Android APK artifact
        uses: actions/upload-artifact@v3
        with:
          name: android-apk
          path: build/app/outputs/flutter-apk/app-release.apk

      - name: Upload iOS archive artifact
        uses: actions/upload-artifact@v3
        with:
          name: ios-archive
          path: build/ios/iphoneos/Runner.app

      - name: Upload Web build artifact
        uses: actions/upload-artifact@v3
        with:
          name: web-build
          path: build/web
